name: Godot CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot Engine & Templates
        uses: actions/cache@v4
        with:
          path: ~/.local/share/godot/
          key: ${{ runner.os }}-godot-4.1.3
          restore-keys: |
            ${{ runner.os }}-godot-

      - name: Windows Export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          export_preset: "Windows Desktop"

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: /home/runner/.local/share/godot/archives/

  export-macos:
    name: macOS Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot Engine & Templates
        uses: actions/cache@v4
        with:
          path: ~/.local/share/godot/
          key: ${{ runner.os }}-godot-4.1.3
          restore-keys: |
            ${{ runner.os }}-godot-

      - name: macOS Export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          export_preset: "macOS"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: /home/runner/.local/share/godot/archives/

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot Engine & Templates
        uses: actions/cache@v4
        with:
          path: ~/.local/share/godot/
          key: ${{ runner.os }}-godot-4.1.3
          restore-keys: |
            ${{ runner.os }}-godot-

      - name: Linux Export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          export_preset: "Linux/X11"

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: /home/runner/.local/share/godot/archives/

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot Engine & Templates
        uses: actions/cache@v4
        with:
          path: ~/.local/share/godot/
          key: ${{ runner.os }}-godot-4.1.3
          restore-keys: |
            ${{ runner.os }}-godot-

      - name: Web Export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          export_preset: "Web"

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: /home/runner/.local/share/godot/archives/
